### PR TITLE
use dockerfile

### PR DESCRIPTION
**Pull request by stephengroat**
starts moving towards using a `Dockerfile` over other types of docker builds

I registered the docker org `anbox` (more than willing to transfer it over), but you can easily take 1-2 mins off of the clean builds by uploading the image to the Hub.

### CODE REVIEW

**Comment by morphis** [comment]
I am fine with having a docker image on docker hub. Can you transfer the Anbox organization to me? My Docker ID is `mrmorph`.

**Comment by stephengroat** [comment]
@morphis org transferred

**Comment by stephengroat** [comment]
anything else needed from me on this?

**Comment by leandromqrs** [comment]
I need this! Im waiting for...

**Pull request merged**
