### PR TITLE
Networking/phys

### PR DESCRIPTION
**Pull request by Xerusial**
This patch targets issue [1213](https://github.com/anbox/anbox/issues/1213).
It creates the possibility to use non-bridged networking in the container, making Anbox
the first Android emulator to be able to test apps with NSD, as far as I know.

Also, all networking is now piped to the Android wifi interface instead of the ethernet interface,
creating a convenient user interface. This makes three types of connections possible:
- Bridged with wired WPA driver and disabled RSSI scanning
- Physical wired with wired WPA driver and disabled RSSI scanning
- Physical wifi with nl80211 or WEXT WPA driver

Two new snap variables have been added, which are documented in the docs repository.
A patch for this will follow any minute.

Wifi is started on boot so one does not have to change the settings before using Anbox.
The wired interface (bridged or physical) looks like this:
Screenshot from 2020-03-07 22-51-31

### CODE REVIEW

**Comment by morphis** [comment]
Thanks for this nice change! I will need some time to look through it and the implications but expect a review from me soon.

**Comment by Nathan22211** [comment]
I hope this gets implemented into the main code. for now though, maybe he can provide the built snap from his branch?

**Comment by PSGXerus** [comment]
> I hope this gets implemented into the main code. for now though, maybe he can provide the built snap from his branch?

Here you go: [Link is valid 2 weeks](https://syncandshare.lrz.de/getlink/fiWAUth5iPrjvyJSbGyJwrnv/)

Documentation can be found [here](https://github.com/anbox/docs/pull/7/commits/aa7f89332a5855795b8dd19332f2830f7df3b65d)

**Comment by PSGXerus** [comment]
@morphis I had a hard time building my snap, because apparently, google broke their swiftshader repo. The mentioned commit in Anbox's snapcraft.yaml cannot be checked out so I had to use an old fork of the swiftshader repo: https://github.com/ben-clayton/swiftshader

**Comment by danvim** [comment]
Is this going to get merged soon?

**Pull request closed without merging**
