### PR TITLE
Update snapcraft.yaml

### PR DESCRIPTION
**Pull request by erikd256**
Added support for aarch64

not yet tested

### CODE REVIEW

**Comment by shlyakpavel** [comment]
Why is not this one merged?

**Comment by Fuseteam** [comment]
> not yet tested

Hmmm good question @shlyakpavel

**Comment by iGorjidooz** [comment]
This would be really useful if merged :)

**Comment by Fuseteam** [comment]
Has this been tested yet? Sounds useful

**Comment by erikd256** [comment]
It isn't fully tested

**Pull request closed without merging**
