### PR TITLE
many: add support for binderfs

### LINKED ISSUE #1273: anbox-support dkms on ubuntu 19.10
Hi, I'm trying to install anbox on ubuntu 19.10.

when adding the PPA I had to lie and use _disco_ as _eoan_ doesn't exist but installing `anbox-modules-dkms` fails as follows:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed
  anbox-modules-dkms
0 to upgrade, 1 to newly install, 0 to remove and 0 not to upgrade.
Need to get 0 B/38.2 kB of archives.
After this operation, 214 kB of additional disk space will be used.
Selecting previously unselected package anbox-modules-dkms.
(Reading database ... 295992 files and directories currently installed.)
Preparing to unpack .../anbox-modules-dkms_13~disco1_all.deb ...
Unpacking anbox-modules-dkms (13~disco1) ...
Setting up anbox-modules-dkms (13~disco1) ...
Loading new anbox-1 DKMS files...
Building for 5.3.0-19-lowlatency
Building initial module for 5.3.0-19-lowlatency
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/anbox-modules-dkms.0.crash'
Error! Bad return status for module build on kernel: 5.3.0-19-lowlatency (x86_64)
Consult /var/lib/dkms/anbox/1/build/make.log for more information.
dpkg: error processing package anbox-modules-dkms (--configure):
 installed anbox-modules-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 anbox-modules-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

make.log
```
DKMS make.log for anbox-1 for kernel 5.3.0-19-lowlatency (x86_64)
Sat 26 Oct 21:35:07 BST 2019
make: Entering directory '/var/lib/dkms/anbox/1/build/ashmem'
make -C /lib/modules/5.3.0-19-lowlatency/build V=0 M=$PWD
make[1]: Entering directory '/usr/src/linux-headers-5.3.0-19-lowlatency'
  CC [M]  /var/lib/dkms/anbox/1/build/ashmem/deps.o
  CC [M]  /var/lib/dkms/anbox/1/build/ashmem/ashmem.o
  LD [M]  /var/lib/dkms/anbox/1/build/ashmem/ashmem_linux.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /var/lib/dkms/anbox/1/build/ashmem/ashmem_linux.mod.o
  LD [M]  /var/lib/dkms/anbox/1/build/ashmem/ashmem_linux.ko
make[1]: Leaving directory '/usr/src/linux-headers-5.3.0-19-lowlatency'
make: Leaving directory '/var/lib/dkms/anbox/1/build/ashmem'
make: Entering directory '/var/lib/dkms/anbox/1/build/binder'
make -C /lib/modules/5.3.0-19-lowlatency/build V=0 M=$PWD
make[1]: Entering directory '/usr/src/linux-headers-5.3.0-19-lowlatency'
  CC [M]  /var/lib/dkms/anbox/1/build/binder/deps.o
  CC [M]  /var/lib/dkms/anbox/1/build/binder/binder.o
In file included from ././include/linux/kconfig.h:5,
                 from <command-line>:
./include/generated/autoconf.h:4088: warning: "CONFIG_ANDROID_BINDER_DEVICES" redefined
 4088 | #define CONFIG_ANDROID_BINDER_DEVICES ""
      | 
<command-line>: note: this is the location of the previous definition
In file included from ././include/linux/kconfig.h:5,
                 from <command-line>:
./include/generated/autoconf.h:4088: warning: "CONFIG_ANDROID_BINDER_DEVICES" redefined
 4088 | #define CONFIG_ANDROID_BINDER_DEVICES ""
      | 
<command-line>: note: this is the location of the previous definition
/var/lib/dkms/anbox/1/build/binder/binder.c:3406:11: error: initialization of ‘vm_fault_t (*)(struct vm_fault *)’ {aka ‘unsigned int (*)(struct vm_fault *)’} from incompatible pointer type ‘int (*)(struct vm_fault *)’ [-Werror=incompatible-pointer-types]
 3406 |  .fault = binder_vm_fault,
      |           ^~~~~~~~~~~~~~~
/var/lib/dkms/anbox/1/build/binder/binder.c:3406:11: note: (near initialization for ‘binder_vm_ops.fault’)
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:288: /var/lib/dkms/anbox/1/build/binder/binder.o] Error 1
make[1]: *** [Makefile:1653: _module_/var/lib/dkms/anbox/1/build/binder] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.3.0-19-lowlatency'
make: *** [Makefile:8: all] Error 2
make: Leaving directory '/var/lib/dkms/anbox/1/build/binder'

```

and `anbox system-info`
```
snap-revision: 158
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: 
  version: 
  snap-based: true
kernel:
  version: Linux version 5.3.0-19-lowlatency (buildd@lgw01-amd64-053) (gcc version 9.2.1 20191008 (Ubuntu 9.2.1-9ubuntu2)) #20-Ubuntu SMP PREEMPT Fri Oct 18 10:13:46 UTC 2019
  binder: false
  ashmem: false
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_IMG_context_priority
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES 3.2 Mesa 18.0.5
    extensions:
      - GL_ANDROID_extension_pack_es31a
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_APPLE_texture_max_level
      - GL_EXT_blend_func_extended
      - GL_EXT_blend_minmax
      - GL_EXT_buffer_storage
      - GL_EXT_clip_cull_distance
      - GL_EXT_color_buffer_float
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_discard_framebuffer
      - GL_EXT_disjoint_timer_query
      - GL_EXT_draw_buffers
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_frag_depth
      - GL_EXT_geometry_point_size
      - GL_EXT_geometry_shader
      - GL_EXT_gpu_shader5
      - GL_EXT_map_buffer_range
      - GL_EXT_multi_draw_arrays
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_primitive_bounding_box
      - GL_EXT_read_format_bgra
      - GL_EXT_robustness
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_framebuffer_fetch
      - GL_EXT_shader_integer_mix
      - GL_EXT_shader_io_blocks
      - GL_EXT_shader_samples_identical
      - GL_EXT_tessellation_point_size
      - GL_EXT_tessellation_shader
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_buffer
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_cube_map_array
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_EXT_unpack_subimage
      - GL_INTEL_conservative_rasterization
      - GL_INTEL_performance_query
      - GL_KHR_blend_equation_advanced
      - GL_KHR_blend_equation_advanced_coherent
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_KHR_no_error
      - GL_KHR_robust_buffer_access_behavior
      - GL_KHR_robustness
      - GL_KHR_texture_compression_astc_ldr
      - GL_KHR_texture_compression_astc_sliced_3d
      - GL_MESA_shader_integer_functions
      - GL_NV_draw_buffers
      - GL_NV_fbo_color_attachments
      - GL_NV_image_formats
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_copy_image
      - GL_OES_depth24
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_geometry_point_size
      - GL_OES_geometry_shader
      - GL_OES_get_program_binary
      - GL_OES_gpu_shader5
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_primitive_bounding_box
      - GL_OES_required_internalformat
      - GL_OES_rgb8_rgba8
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_image_atomic
      - GL_OES_shader_io_blocks
      - GL_OES_shader_multisample_interpolation
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_surfaceless_context
      - GL_OES_tessellation_point_size
      - GL_OES_tessellation_shader
      - GL_OES_texture_3D
      - GL_OES_texture_border_clamp
      - GL_OES_texture_buffer
      - GL_OES_texture_cube_map_array
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_texture_stencil8
      - GL_OES_texture_storage_multisample_2d_array
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float
      - GL_OES_viewport_array
```

### PR DESCRIPTION
**Pull request by morphis**
binderfs is a new in kernel filesystem which abstracts dynamic
allocation of binder devices and makes it suitable for in container
use. See https://www.kernel.org/doc/html/latest/admin-guide/binderfs.html
and https://brauner.github.io/2019/01/09/android-binderfs.html for more
details.

We use binderfs when available (starting with Ubuntu 19.04 and its
standard kernel) and otherwise fallback to the static /dev/binder if
available.

Fixes #1273

### CODE REVIEW

**Comment by Spurlos** [comment]
Any ETA on when this PR could be merged?

**Comment by fuzepod** [comment]
Is this pull request included in the current snap build?

**Comment by Entropy512** [comment]
@morphis implied that it is in a comment on #1316 - but it's impossible to tell since all indications given by anbox are that it's not present.  If it's just a display bug in anbox system-info, this is a pretty big bug since it leaves the user no way to figure out why anbox isn't working, and the ONLY hint as a starting point for troubleshooting that they have is evidence binder isn't working even though the module is loaded.

**Comment by DennisHeine** [comment]
binder self compiled binder module from anobox github repo cant be installed because it would overwrite the module which has been compiled into the kernel. module provided by kernel 5something+ does only use binderfs.

workaround:

mkdir /dev/binder
mount -t binder binder /dev/binder

also, i updated the snap version to the latest beta.
afterwards, anbox ran on (x)ubuntu 20.04

**Comment by MuriloEduardo** [comment]
> self compiled binder module from anobox github repo can't be installed because it would overwrite the module which has been compiled into the kernel. this state won't allow anbox to run, as the module provided by kernel 5something+ does only use binderfs, but no /dev/binder
> 
> workaround:
> 
> mkdir /dev/binder
> mount -t binder binder /dev/binder
> 
> also, i updated the snap version to the latest beta.
> afterwards, anbox ran on (x)ubuntu 20.04


after a long time, that's the only way it worked for me! Thank you so much!

**Comment by Manouchehri** [comment]
@decipher2k I can confirm that your workaround is still needed for me on both Ubuntu 18.04 and 20.04.

```sh
sudo add-apt-repository ppa:morphis/anbox-support
sudo apt update
sudo apt install linux-headers-generic anbox-modules-dkms
sudo mkdir /dev/binder
sudo mount -t binder binder /dev/binder
sudo snap install --devmode --beta anbox
anbox system-info # works now
```

**Comment by Fuseteam** [comment]
@Manouchehri you shouldn't need the ppa post 19.04

**Pull request merged**
