### PR TITLE
replace deprecated vfs_read with kernel_read

### PR DESCRIPTION
**Pull request by sarangnemo**
vfs_read is no longer exported from kernel 4.14 (see #486). A related issue with ashmem and ZFS was resolved by replacing vfs_read with kernel_read:
https://github.com/zfsonlinux/spl/issues/656

### CODE REVIEW

**Comment by hacker1024** [comment]
This has fixed the issue for me as well, please merge.

**Comment by morphis** [comment]
Does this work with older kernels as well?

**Comment by sarangnemo** [comment]
I can't test exhaustively, but it also works for me with kernel 4.9.  According to [this](https://github.com/zfsonlinux/spl/pull/659), kernel_read should replace vfs_read from kernel 3.9.

**Comment by timofonic** [comment]
@zergling-man @sarangnemo @vasishath @hacker1024  @morphis   The Pull Request doesn't seem applied upstream yet. WHY? No updates since Nov 2017. Are there any developer alive? What about assign commit privileges to more interested developers?

**Comment by oopen** [comment]
What do you expect to merge ???
Pre 3.9 kernel distrib ?
But you "only" support up 14.04 ubuntu witch is 3.13 kernel !!!
2 lts version but not recent 17.10 ubuntu ....... lol
Plese merge, we need it for all up to date distro aka ubuntu 17.10 & archlinux
you live in past

@timofonic "What about assign commit privileges to more interested developers?" Good idea.

But it is a generic GIT problem, we need other democratical method, that git doen't provide today, like vote to merge ...
What append when mainterner die/not active ? multiple fork ? this will a serious issue for foss

**Pull request merged**
