### PR TITLE
Fix narrowing conversion inside {} (Boost 1.66)

### PR DESCRIPTION
**Pull request by modscleo4**
add static_cast<int>() on pool_size_ casting to avoid narrowing conversion errors

### CODE REVIEW

**Comment by modscleo4** [comment]
Okay, there's another narrowing conversion in line 58

/anbox/src/anbox/runtime.cpp:58:27: error: narrowing conversion of '(int)((anbox::Runtime*)this)->anbox::Runtime::pool_size_' from 'int' to 'std::size_t {aka long unsigned int}' inside { } [-Werror=narrowing]

**Comment by mcku** [comment]
This only works if boost is 1.66, but fails on 1.65.

**Comment by jacksondm33** [comment]
What is keeping this from being merged?

**Comment by morphis** [comment]
@jacksondm33 Me not having time :-)

**Comment by jacksondm33** [comment]
Are there more changes necessary or something?
If not, can't you just merge it?

**Comment by jacksondm33** [comment]
This would fix the AUR build. I'm guessing the program still wouldn't work completely normal with the newer boost version but I'm not really sure.

**Comment by morphis** [comment]
@jacksondm33 I had to merge the PR with master to make CI and github happy. Now its time to merge it :-)

**Pull request merged**
