### PR TITLE
Added Intel Core 2 Duo P7550 to whitelist

### PR DESCRIPTION
**Pull request by us41242**

### CODE REVIEW

**Comment by morphis** [comment]
Is this still necessary with https://github.com/anbox/anbox/pull/912 being merged? Did you try the latest snap from the edge channel which includes this fix?

**Comment by Petitswood1** [comment]
Also same issue with Intel Core Duo E4500
Have check the Edge Channel snap which does not resolve this issue 
(Am newbie to this so if improper comment etc  please advise and will open up separate pull request)

**Comment by morphis** [comment]
@Petitswood1 You will not have any luck with the E4500 as according to http://www.cpu-world.com/CPUs/Core_2/Intel-Core%202%20Duo%20E4500%20HH80557PG0492M%20(BX80557E4500).html it misses support for SSE 4.1/4.2 which is mandatory for Anbox.

**Comment by morphis** [comment]
@us41242 Did you verify Anbox starts with this PR? According to http://www.cpu-world.com/CPUs/Core_2/Intel-Core%202%20Duo%20Mobile%20P7550%20AW80577SH0513MA.html your CPU misses SSE 4.2 which is mandatory for Anbox to work. Adding your CPU to the whitelist wont help unless we hit some kind of corner case.

**Comment by Petitswood1** [comment]
Thanks v much.  Sorry for putting you to the bother of dealing with this

Adrian

**Comment by morphis** [comment]
Closing as no response from author after ~1 month.

**Pull request closed without merging**
