### PR TITLE
WIP: mount binderfs

### PR DESCRIPTION
**Pull request by Fuseteam**

### CODE REVIEW

**Comment by Fuseteam** [comment]
oops uh

**Comment by morphis** [comment]
What is the purpose of this PR? Mouting binderfs is done here https://github.com/anbox/anbox/blob/master/scripts/container-manager.sh#L99

**Comment by Fuseteam** [comment]
> What is the purpose of this PR? Mouting binderfs is done here https://github.com/anbox/anbox/blob/master/scripts/container-manager.sh#L99

this pr was an attempt to get anbox itself to mount binderfs

**Comment by Fuseteam** [comment]
i don't think i'll find the chance to figure this out properly

**Pull request closed without merging**
