### PR TITLE
fix no switch default and old-style-cast errors (gcc 10)

### PR DESCRIPTION
**Pull request by vaurelios**

### CODE REVIEW

**Comment by zhsj** [comment]
hmm, `-Wno-error=old-style-cast` is already set in `external/backward-cpp/CMakeLists.txt`, and `-Wno-error=switch-default` is in `external/cpu_features/CMakeLists.txt`. Not sure why the compiler still complains, could you paste the log?

**Comment by morphis** [comment]
@zhsj #810 seems to be related to this one and has logs.

**Comment by zhsj** [comment]
no, #801 complains `-Werror=switch-default` in backward-cpp.

**Comment by zhsj** [comment]
btw, if I understand correctly, the current development version of gcc is 9, not sure where gcc 10 comes from...

**Comment by vaurelios** [comment]
@morphis I've opened a issue bombela/backward-cpp#122

**Pull request closed without merging**
